# Generated by Django 3.0.5 on 2020-06-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_auto_20200622_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogvalue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
